version: 2

variables:

  SOOS_PROJECT_NAME: "SOOS-DAST-Bamboo-Test"
  SOOS_SCAN_MODE: "baseline"
  SOOS_API_BASE_URL: "https://dev-api.soos.io/api/"
  SOOS_TARGET_URL: "https://soos-dast-juice-shop.herokuapp.com/"

  

plan:
  project-key: DAST
  name: SOOS Analysis
  key: SOOS
  

stages:
  - Run SOOS analysis:
    - Run analysis
    

Run analysis:
  docker:
    image: docker:stable-dind
    #volumes: 
     # "/var/run/docker.sock": "/var/run/docker.sock"
  tasks:
        # hello-world
        # OKK
        # PARAMS="--clientId=${bamboo.SOOS_CLIENT_ID} --apiKey=${bamboo.SOOS_API_KEY} --projectName=\"${bamboo.SOOS_PROJECT_NAME}\" --scanMode=${bamboo.SOOS_SCAN_MODE} --apiURL=${bamboo.SOOS_API_BASE_URL}"
        # docker run --rm ghcr.io/soos-abenassi/dast:0.6 ${bamboo.SOOS_TARGET_URL} $PARAMS 
        ###
    - script: |
        PARAMS="--clientId=${bamboo.SOOS_CLIENT_ID} --apiKey=${bamboo.SOOS_API_KEY} --projectName=${bamboo.SOOS_PROJECT_NAME} --scanMode=${bamboo.SOOS_SCAN_MODE} --apiURL=${bamboo.SOOS_API_BASE_URL}"

        echo $PARAMS
        echo '${bamboo.SOOS_DEBUG}'
        echo '${bamboo.SOOS_AJAX_SPIDER}'

        if [  -z '${bamboo.SOOS_DEBUG}' == "true" ]; then
            PARAMS="$PARAMS --debug"
            echo "OK 1er IF"
        fi
        if [  -z '${bamboo.SOOS_AJAX_SPIDER}' == "true" ]; then
            PARAMS="$PARAMS --ajaxSpider"
            echo "OK 2do IF"
            echo $PARAMS
        fi
        if [  -z '${bamboo.SOOS_RULES}' != "" ]; then
            PARAMS="$PARAMS --rules=${bamboo.SOOS_RULES}"
        fi
        if [  -z '${bamboo.SOOS_CONTEXT_FILE}' != "" ]; then
            PARAMS="$PARAMS --contextFile=${bamboo.SOOS_CONTEXT_FILE}"
        fi
        if [  -z '${bamboo.SOOS_CONTEXT_USER}' != "" ]; then
            PARAMS="$PARAMS --contextUser=${bamboo.SOOS_CONTEXT_USER}"
        fi
        if [  -z '${bamboo.SOOS_FULL_SCAN_MINUTES}' != "" ]; then
            PARAMS="$PARAMS --fullScanMinutes=${bamboo.SOOS_FULL_SCAN_MINUTES}"
        fi
        if [  -z '${bamboo.SOOS_API_SCAN_FORMAT}' != "" ]; then
            PARAMS="$PARAMS --apiScanFormat=${bamboo.SOOS_API_SCAN_FORMAT}"
        fi
        if [  -z '${bamboo.bamboo.SOOS_LEVEL}' != "" ]; then
            PARAMS="$PARAMS --level=${bamboo.SOOS_LEVEL}"
        fi
        
        docker run -w /zap --rm ghcr.io/soos-abenassi/dast:0.6 ${bamboo.SOOS_TARGET_URL} $PARAMS

        



        