version: 2

variables:

  SOOS_PROJECT_NAME: "SOOS-DAST-Bamboo-Test"
  SOOS_SCAN_MODE: 'baseline'
  SOOS_API_BASE_URL: "https://dev-api.soos.io/api/"
  SOOS_TARGET_URL: "https://soos-dast-juice-shop.herokuapp.com/"
  

plan:
  project-key: DAST
  name: SOOS Analysis
  key: SOOS
  

stages:
  - Run SOOS analysis:
    - Run analysis
    

Run analysis:
  docker:
    image: docker:dind
    volumes: 
      "/var/run/docker.sock": "/var/run/docker.sock"
    use-default-volumes: false
    #docker-run-arguments:
    #- --privileged
  tasks:
      # ghcr.io/soos-abenassi/dast:0.6 --clientId=${bamboo.SOOS_CLIENT_ID} --apiKey=${bamboo.SOOS_API_KEY} --projectName=\"${bamboo.SOOS_PROJECT_NAME}\" --scanMode=${bamboo.SOOS_SCAN_MODE} --apiURL=${bamboo.SOOS_API_BASE_URL}" --integrationName="Bamboo" ${bamboo.TARGET_URL}
        # docker run --rm hello-world
    - script: |
        echo "OK"
        