version: 2

variables:

  SOOS_PROJECT_NAME: "SOOS-DAST-Bamboo-Test"
  SOOS_SCAN_MODE: 'baseline'
  SOOS_API_BASE_URL: "https://dev-api.soos.io/api/"
  SOOS_TARGET_URL: "https://soos-dast-juice-shop.herokuapp.com/"
  

plan:
  project-key: DAST
  name: SOOS Analysis
  key: SOOS
  

stages:
  - Run SOOS analysis:
    - Run analysis
    

Run analysis:
  docker:
    image: docker:stable-dind
    volumes: 
      "/var/run/docker.sock": "/var/run/docker.sock"
  tasks:
        # hello-world
        # OKK
        # PARAMS="--clientId=${bamboo.SOOS_CLIENT_ID} --apiKey=${bamboo.SOOS_API_KEY} --projectName=\"${bamboo.SOOS_PROJECT_NAME}\" --scanMode=${bamboo.SOOS_SCAN_MODE} --apiURL=${bamboo.SOOS_API_BASE_URL}"
        # docker run --rm ghcr.io/soos-abenassi/dast:0.6 ${bamboo.SOOS_TARGET_URL} $PARAMS 
        ###
    - script: |

        PARAMS="--clientId=${bamboo.SOOS_CLIENT_ID} --apiKey=${bamboo.SOOS_API_KEY} --projectName="${bamboo.SOOS_PROJECT_NAME} --scanMode=${bamboo.SOOS_SCAN_MODE} --apiURL=${bamboo.SOOS_API_BASE_URL}"
        
        if [  ${bamboo.SOOS_DEBUG} == "true" ]; then
            PARAMS+=" --debug"
        fi
        if [  ${bamboo.SOOS_AJAX_SPIDER} == "true" ]; then
            PARAMS+=" --ajaxSpider"
        fi
        if [  ${bamboo.SOOS_RULES} != "" ]; then
            PARAMS+=" --rules="${bamboo.SOOS_RULES}
        fi
        if [  ${bamboo.SOOS_CONTEXT_FILE} != "" ]; then
            PARAMS+=" --contextFile="${bamboo.SOOS_CONTEXT_FILE}
        fi
        if [  ${bamboo.SOOS_CONTEXT_USER} != "" ]; then
            PARAMS+=" --contextUser="${bamboo.SOOS_CONTEXT_USER}
        fi
        if [  ${bamboo.SOOS_FULL_SCAN_MINUTES} != "" ]; then
            PARAMS+=" --fullScanMinutes="${bamboo.SOOS_FULL_SCAN_MINUTES}
        fi
        if [  ${bamboo.SOOS_API_SCAN_FORMAT} != "" ]; then
            PARAMS+=" --apiScanFormat="${bamboo.SOOS_API_SCAN_FORMAT}
        fi
        if [  ${bamboo.bamboo.SOOS_LEVEL} != "" ]; then
            PARAMS+=" --level="${bamboo.SOOS_LEVEL}
        fi
        
        docker run -w /zap --rm ghcr.io/soos-abenassi/dast:0.6 ${bamboo.SOOS_TARGET_URL} $PARAMS

        