version: 2

variables:

  SOOS_PROJECT_NAME: "SOOS-DAST-Bamboo-Test"
  SOOS_SCAN_MODE: 'baseline'
  SOOS_API_BASE_URL: "https://dev-api.soos.io/api/"
  SOOS_TARGET_URL: "https://soos-dast-juice-shop.herokuapp.com/"
  

plan:
  project-key: DAST
  name: SOOS Analysis
  key: SOOS
  

stages:
  - Run SOOS analysis:
    - Run analysis
    

Run analysis:
  docker:
    image: ghcr.io/soos-abenassi/dast:0.6
  tasks:
    - script: |
        #!/bin/bash

        echo "OK"